trigger:
  branches:
    include:
      - build

variables:
  ACR_NAME: 'AcrEftGrupo06' 
  IMAGE_NAME: 'appweb-eft-grupo06'
  SERVICE_CONNECTION_NAME: 'acr-eft-grupo06-service-cnx' 

jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build y Push de la imagen Docker al ACR - App Web EFT Grupo 06'
          

          